#!/usr/bin/env python3
"""
sha256_manifest.py — Compute SHA-256 hashes for all files in the repository root.
Output: HASH_MANIFEST.txt
"""

import hashlib
import os

REPO_ROOT = os.path.dirname(os.path.abspath(__file__))
OUTPUT_FILE = os.path.join(REPO_ROOT, "HASH_MANIFEST.txt")

# Collect all regular files in root (not directories, not .git, not the manifest itself)
files = []
for entry in sorted(os.listdir(REPO_ROOT)):
    full_path = os.path.join(REPO_ROOT, entry)
    if os.path.isfile(full_path) and not entry.startswith('.') and entry != "HASH_MANIFEST.txt":
        files.append(entry)

# Compute hashes
results = []
max_name_len = max(len(f) for f in files) if files else 0
for fname in files:
    full_path = os.path.join(REPO_ROOT, fname)
    sha256 = hashlib.sha256()
    with open(full_path, "rb") as f:
        for chunk in iter(lambda: f.read(8192), b""):
            sha256.update(chunk)
    results.append((fname, sha256.hexdigest()))

# Write manifest
with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
    f.write("SHA-256 HASH MANIFEST\n")
    f.write(f"Generated by: sha256_manifest.py\n")
    f.write(f"Files in: {REPO_ROOT}\n")
    f.write("=" * (max_name_len + 68) + "\n\n")
    f.write(f"{'File':<{max_name_len + 4}} SHA-256\n")
    f.write(f"{'-' * (max_name_len + 2)}  {'-' * 64}\n")
    for fname, digest in results:
        f.write(f"{fname:<{max_name_len + 4}} {digest}\n")
    f.write(f"\nTotal files: {len(results)}\n")

print(f"Manifest written to {OUTPUT_FILE}")
print(f"Total files hashed: {len(results)}")
